apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-production

resources:
  - ../../base

nameSuffix: -prod

commonLabels:
  environment: production

replicas:
  - name: product-service
    count: 3
  - name: order-service
    count: 3
  - name: gateway
    count: 3
  - name: authentication
    count: 2

images:
  - name: ecommerce-config
    newName: asia-southeast1-docker.pkg.dev/btl-ecommerce-prod-478907/ecommerce-repo/ecommerce-config
    newTag: prod-latest
  - name: ecommerce-discovery-server
    newName: asia-southeast1-docker.pkg.dev/btl-ecommerce-prod-478907/ecommerce-repo/ecommerce-discovery-server
    newTag: prod-latest
  - name: ecommerce-gateway
    newName: asia-southeast1-docker.pkg.dev/btl-ecommerce-prod-478907/ecommerce-repo/ecommerce-gateway
    newTag: prod-latest
  - name: ecommerce-authentication
    newName: asia-southeast1-docker.pkg.dev/btl-ecommerce-prod-478907/ecommerce-repo/ecommerce-authentication
    newTag: prod-latest
  - name: ecommerce-product
    newName: asia-southeast1-docker.pkg.dev/btl-ecommerce-prod-478907/ecommerce-repo/ecommerce-product
    newTag: prod-latest
  - name: ecommerce-order
    newName: asia-southeast1-docker.pkg.dev/btl-ecommerce-prod-478907/ecommerce-repo/ecommerce-order
    newTag: prod-latest
  - name: ecommerce-monitoring
    newName: asia-southeast1-docker.pkg.dev/btl-ecommerce-prod-478907/ecommerce-repo/ecommerce-monitoring
    newTag: prod-latest