apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-production

#bases:
#  - ../../base

nameSuffix: -prod

commonLabels:
  environment: production

replicas:
  - name: product-service
    count: 3
  - name: order-service
    count: 3
  - name: gateway
    count: 3
  - name: authentication
    count: 2

images:
  - name: cinnamoll/ecommerce-config
    newTag: prod-latest
  - name: cinnamoll/ecommerce-discovery-server
    newTag: prod-latest
  - name: cinnamoll/ecommerce-gateway
    newTag: prod-latest
  - name: cinnamoll/ecommerce-authentication
    newTag: prod-latest
  - name: cinnamoll/ecommerce-product
    newTag: prod-latest
  - name: cinnamoll/ecommerce-order
    newTag: prod-latest
  - name: cinnamoll/ecommerce-monitoring
    newTag: prod-latest