apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-staging

#bases:
#  - ../../base

nameSuffix: -staging

commonLabels:
  environment: staging

replicas:
  - name: product-service
    count: 1
  - name: order-service
    count: 1
  - name: gateway
    count: 1
  - name: authentication
    count: 1
#
#patchesStrategicMerge:
#  - dispatch-replicas.yaml

images:
  - name: cinnamoll/ecommerce-config
    newTag: staging-latest
  - name: cinnamoll/ecommerce-discovery-server
    newTag: staging-latest
  - name: cinnamoll/ecommerce-gateway
    newTag: staging-latest
  - name: cinnamoll/ecommerce-authentication
    newTag: staging-latest
  - name: cinnamoll/ecommerce-product
    newTag: staging-latest
  - name: cinnamoll/ecommerce-order
    newTag: staging-latest
  - name: cinnamoll/ecommerce-monitoring
    newTag: staging-latest