apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-staging

bases:
  - ../../base

nameSuffix: -staging

commonLabels:
  environment: staging

replicas:
  - name: product-service
    count: 1
  - name: order-service
    count: 1
  - name: gateway
    count: 1
  - name: authentication
    count: 1

patchesStrategicMerge:
  - patch-replicas.yaml

images:
  - name: your-dockerhub-username/ecommerce-config
    newTag: staging-latest
  - name: your-dockerhub-username/ecommerce-discovery-server
    newTag: staging-latest
  - name: your-dockerhub-username/ecommerce-gateway
    newTag: staging-latest
  - name: your-dockerhub-username/ecommerce-authentication
    newTag: staging-latest
  - name: your-dockerhub-username/ecommerce-product
    newTag: staging-latest
  - name: your-dockerhub-username/ecommerce-order
    newTag: staging-latest
  - name: your-dockerhub-username/ecommerce-monitoring
    newTag: staging-latest